//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找已本地化的字符串等等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GlobalResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.GlobalResource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找重写当前线程的 CurrentUICulture 
        /// 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Contact Person 联系人 的本地化字符串。
        /// </summary>
        internal static string contact_person {
            get {
                return ResourceManager.GetString("contact_person", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create Time 创建时间 的本地化字符串。
        /// </summary>
        internal static string create_time {
            get {
                return ResourceManager.GetString("create_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Customer Create 客户添加 的本地化字符串。
        /// </summary>
        internal static string customer_create {
            get {
                return ResourceManager.GetString("customer_create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Customer Management 客户管理 的本地化字符串。
        /// </summary>
        internal static string customer_management {
            get {
                return ResourceManager.GetString("customer_management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Customer Name 客户名称 的本地化字符串。
        /// </summary>
        internal static string customer_name {
            get {
                return ResourceManager.GetString("customer_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Customer Search 客户查询 的本地化字符串。
        /// </summary>
        internal static string customer_query {
            get {
                return ResourceManager.GetString("customer_query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Customer Update 客户修改 的本地化字符串。
        /// </summary>
        internal static string customer_update {
            get {
                return ResourceManager.GetString("customer_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Customer Verify 客户审核 的本地化字符串。
        /// </summary>
        internal static string customer_verify {
            get {
                return ResourceManager.GetString("customer_verify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 End Customer Name 终用户名称 的本地化字符串。
        /// </summary>
        internal static string end_customer_name {
            get {
                return ResourceManager.GetString("end_customer_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Faulty Description 故障描述 的本地化字符串。
        /// </summary>
        internal static string failure_description {
            get {
                return ResourceManager.GetString("failure_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Firmware Version 固件版本 的本地化字符串。
        /// </summary>
        internal static string firmware_version {
            get {
                return ResourceManager.GetString("firmware_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Login 登录 的本地化字符串。
        /// </summary>
        internal static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Logout 登出 的本地化字符串。
        /// </summary>
        internal static string logout {
            get {
                return ResourceManager.GetString("logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mobile 手机 的本地化字符串。
        /// </summary>
        internal static string mobile {
            get {
                return ResourceManager.GetString("mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 My Task 我的任务 的本地化字符串。
        /// </summary>
        internal static string mytask {
            get {
                return ResourceManager.GetString("mytask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OK 确定 的本地化字符串。
        /// </summary>
        internal static string ok {
            get {
                return ResourceManager.GetString("ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Operation 操作 的本地化字符串。
        /// </summary>
        internal static string operation {
            get {
                return ResourceManager.GetString("operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ordering Number 订货号 的本地化字符串。
        /// </summary>
        internal static string ordering_number {
            get {
                return ResourceManager.GetString("ordering_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Order Create 创建工单 的本地化字符串。
        /// </summary>
        internal static string order_create {
            get {
                return ResourceManager.GetString("order_create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Work Order Id 工单号 的本地化字符串。
        /// </summary>
        internal static string order_id {
            get {
                return ResourceManager.GetString("order_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Order Search 工单查询  的本地化字符串。
        /// </summary>
        internal static string order_query {
            get {
                return ResourceManager.GetString("order_query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Work Order Status 工单状态 的本地化字符串。
        /// </summary>
        internal static string order_status {
            get {
                return ResourceManager.GetString("order_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password 密码 的本地化字符串。
        /// </summary>
        internal static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Post Code 邮编 的本地化字符串。
        /// </summary>
        internal static string postcode {
            get {
                return ResourceManager.GetString("postcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Module Type 工具型号 的本地化字符串。
        /// </summary>
        internal static string product_name {
            get {
                return ResourceManager.GetString("product_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remarks 备注 的本地化字符串。
        /// </summary>
        internal static string remark {
            get {
                return ResourceManager.GetString("remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Serial Number 序列号 的本地化字符串。
        /// </summary>
        internal static string serial_number {
            get {
                return ResourceManager.GetString("serial_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Telephone 电话 的本地化字符串。
        /// </summary>
        internal static string telephone {
            get {
                return ResourceManager.GetString("telephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User Name 用户名 的本地化字符串。
        /// </summary>
        internal static string username {
            get {
                return ResourceManager.GetString("username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User Create 用户添加 的本地化字符串。
        /// </summary>
        internal static string user_create {
            get {
                return ResourceManager.GetString("user_create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User Management 用户管理 的本地化字符串。
        /// </summary>
        internal static string user_management {
            get {
                return ResourceManager.GetString("user_management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User Search 用户查询 的本地化字符串。
        /// </summary>
        internal static string user_query {
            get {
                return ResourceManager.GetString("user_query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User Update 用户修改 的本地化字符串。
        /// </summary>
        internal static string user_update {
            get {
                return ResourceManager.GetString("user_update", resourceCulture);
            }
        }
    }
}
