//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找已本地化的字符串等等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GlobalResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.GlobalResource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找重写当前线程的 CurrentUICulture 
        /// 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Address 地址 的本地化字符串。
        /// </summary>
        internal static string address {
            get {
                return ResourceManager.GetString("address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Amount 数量 的本地化字符串。
        /// </summary>
        internal static string amount {
            get {
                return ResourceManager.GetString("amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 City 城市 的本地化字符串。
        /// </summary>
        internal static string city {
            get {
                return ResourceManager.GetString("city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Contact Person 联系人 的本地化字符串。
        /// </summary>
        internal static string contact_person {
            get {
                return ResourceManager.GetString("contact_person", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create Time 创建时间 的本地化字符串。
        /// </summary>
        internal static string create_time {
            get {
                return ResourceManager.GetString("create_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current Status 当前状态 的本地化字符串。
        /// </summary>
        internal static string current_status {
            get {
                return ResourceManager.GetString("current_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Customer 客户 的本地化字符串。
        /// </summary>
        internal static string customer {
            get {
                return ResourceManager.GetString("customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Customer Create 客户添加 的本地化字符串。
        /// </summary>
        internal static string customer_create {
            get {
                return ResourceManager.GetString("customer_create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Customer Id 客户编号 的本地化字符串。
        /// </summary>
        internal static string customer_id {
            get {
                return ResourceManager.GetString("customer_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Customer Management 客户管理 的本地化字符串。
        /// </summary>
        internal static string customer_management {
            get {
                return ResourceManager.GetString("customer_management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Customer Name 客户名称 的本地化字符串。
        /// </summary>
        internal static string customer_name {
            get {
                return ResourceManager.GetString("customer_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Customer Search 客户查询 的本地化字符串。
        /// </summary>
        internal static string customer_query {
            get {
                return ResourceManager.GetString("customer_query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Customer Update 客户修改 的本地化字符串。
        /// </summary>
        internal static string customer_update {
            get {
                return ResourceManager.GetString("customer_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Customer Verify 客户审核 的本地化字符串。
        /// </summary>
        internal static string customer_verify {
            get {
                return ResourceManager.GetString("customer_verify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 缺省特征信息 的本地化字符串。
        /// </summary>
        internal static string default_character {
            get {
                return ResourceManager.GetString("default_character", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit 编辑 的本地化字符串。
        /// </summary>
        internal static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Email 电子邮件 的本地化字符串。
        /// </summary>
        internal static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工号 的本地化字符串。
        /// </summary>
        internal static string emp_code {
            get {
                return ResourceManager.GetString("emp_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 End Customer Name 终用户名称 的本地化字符串。
        /// </summary>
        internal static string end_customer_name {
            get {
                return ResourceManager.GetString("end_customer_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 End Time 结束时间 的本地化字符串。
        /// </summary>
        internal static string end_time {
            get {
                return ResourceManager.GetString("end_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Faulty Description 故障描述 的本地化字符串。
        /// </summary>
        internal static string failure_description {
            get {
                return ResourceManager.GetString("failure_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Firmware 固件版本 的本地化字符串。
        /// </summary>
        internal static string firmware_version {
            get {
                return ResourceManager.GetString("firmware_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Image 图片 的本地化字符串。
        /// </summary>
        internal static string image {
            get {
                return ResourceManager.GetString("image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Inspection Result 检查及结果 的本地化字符串。
        /// </summary>
        internal static string inspection_result {
            get {
                return ResourceManager.GetString("inspection_result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Inspection Result And Tool Function Test 检查结果及工具功能测试 的本地化字符串。
        /// </summary>
        internal static string inspection_result_and_tool_function_test {
            get {
                return ResourceManager.GetString("inspection_result_and_tool_function_test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Appearance Check 外观检查 的本地化字符串。
        /// </summary>
        internal static string inspection_result_item_text1 {
            get {
                return ResourceManager.GetString("inspection_result_item_text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Servo Driver 伺服驱动 的本地化字符串。
        /// </summary>
        internal static string inspection_result_item_text10 {
            get {
                return ResourceManager.GetString("inspection_result_item_text10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 I/O and CPU I/O及CPU 的本地化字符串。
        /// </summary>
        internal static string inspection_result_item_text11 {
            get {
                return ResourceManager.GetString("inspection_result_item_text11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Power Supply 电源 的本地化字符串。
        /// </summary>
        internal static string inspection_result_item_text12 {
            get {
                return ResourceManager.GetString("inspection_result_item_text12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Front Panel 前面板 的本地化字符串。
        /// </summary>
        internal static string inspection_result_item_text13 {
            get {
                return ResourceManager.GetString("inspection_result_item_text13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Display 显示 的本地化字符串。
        /// </summary>
        internal static string inspection_result_item_text14 {
            get {
                return ResourceManager.GetString("inspection_result_item_text14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clutch 离合器 的本地化字符串。
        /// </summary>
        internal static string inspection_result_item_text15 {
            get {
                return ResourceManager.GetString("inspection_result_item_text15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Memory Board 记忆卡 的本地化字符串。
        /// </summary>
        internal static string inspection_result_item_text16 {
            get {
                return ResourceManager.GetString("inspection_result_item_text16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Phisycal Connections 物理连接 的本地化字符串。
        /// </summary>
        internal static string inspection_result_item_text17 {
            get {
                return ResourceManager.GetString("inspection_result_item_text17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mechnical Parts 机械部件 的本地化字符串。
        /// </summary>
        internal static string inspection_result_item_text18 {
            get {
                return ResourceManager.GetString("inspection_result_item_text18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Anglehead Frontpart 弯头总成或输出轴组件 的本地化字符串。
        /// </summary>
        internal static string inspection_result_item_text2 {
            get {
                return ResourceManager.GetString("inspection_result_item_text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Planetary Gear Unit 行星齿轮装置 的本地化字符串。
        /// </summary>
        internal static string inspection_result_item_text3 {
            get {
                return ResourceManager.GetString("inspection_result_item_text3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Transducer 传感器 的本地化字符串。
        /// </summary>
        internal static string inspection_result_item_text4 {
            get {
                return ResourceManager.GetString("inspection_result_item_text4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Motor 马达 的本地化字符串。
        /// </summary>
        internal static string inspection_result_item_text5 {
            get {
                return ResourceManager.GetString("inspection_result_item_text5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Handle &amp; Memory Card 手柄及主板 的本地化字符串。
        /// </summary>
        internal static string inspection_result_item_text6 {
            get {
                return ResourceManager.GetString("inspection_result_item_text6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clutch Pulse Unit 离合器或脉冲单元 的本地化字符串。
        /// </summary>
        internal static string inspection_result_item_text7 {
            get {
                return ResourceManager.GetString("inspection_result_item_text7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Trigger System 开关系统 的本地化字符串。
        /// </summary>
        internal static string inspection_result_item_text8 {
            get {
                return ResourceManager.GetString("inspection_result_item_text8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Other Parts 其他部件 的本地化字符串。
        /// </summary>
        internal static string inspection_result_item_text9 {
            get {
                return ResourceManager.GetString("inspection_result_item_text9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Login 登录 的本地化字符串。
        /// </summary>
        internal static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Logout 登出 的本地化字符串。
        /// </summary>
        internal static string logout {
            get {
                return ResourceManager.GetString("logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mobile 手机 的本地化字符串。
        /// </summary>
        internal static string mobile {
            get {
                return ResourceManager.GetString("mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 My Task 我的任务 的本地化字符串。
        /// </summary>
        internal static string mytask {
            get {
                return ResourceManager.GetString("mytask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OK 确定 的本地化字符串。
        /// </summary>
        internal static string ok {
            get {
                return ResourceManager.GetString("ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Handling 操作 的本地化字符串。
        /// </summary>
        internal static string operation {
            get {
                return ResourceManager.GetString("operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Part Number 订货号 的本地化字符串。
        /// </summary>
        internal static string ordering_number {
            get {
                return ResourceManager.GetString("ordering_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New Order Creation 创建工单 的本地化字符串。
        /// </summary>
        internal static string order_create {
            get {
                return ResourceManager.GetString("order_create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建者 的本地化字符串。
        /// </summary>
        internal static string order_creator {
            get {
                return ResourceManager.GetString("order_creator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Work Order Number 工单号 的本地化字符串。
        /// </summary>
        internal static string order_id {
            get {
                return ResourceManager.GetString("order_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 管理者 的本地化字符串。
        /// </summary>
        internal static string order_manager {
            get {
                return ResourceManager.GetString("order_manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Work Order Searching 工单查询  的本地化字符串。
        /// </summary>
        internal static string order_query {
            get {
                return ResourceManager.GetString("order_query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Work Order Status 工单状态 的本地化字符串。
        /// </summary>
        internal static string order_status {
            get {
                return ResourceManager.GetString("order_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Awaiting for Customer Authorization 等待客户审核 的本地化字符串。
        /// </summary>
        internal static string order_status_1 {
            get {
                return ResourceManager.GetString("order_status_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Awaiting for Check 等待检查 的本地化字符串。
        /// </summary>
        internal static string order_status_2 {
            get {
                return ResourceManager.GetString("order_status_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Awaiting for Quotation 等待报价 的本地化字符串。
        /// </summary>
        internal static string order_status_3 {
            get {
                return ResourceManager.GetString("order_status_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Awaiting for Customer Confirmation 等待客户确认 的本地化字符串。
        /// </summary>
        internal static string order_status_4 {
            get {
                return ResourceManager.GetString("order_status_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Awaiting for Spare Parts 等待备件到齐 的本地化字符串。
        /// </summary>
        internal static string order_status_5 {
            get {
                return ResourceManager.GetString("order_status_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Awaiting for Repair 等待维修 的本地化字符串。
        /// </summary>
        internal static string order_status_6 {
            get {
                return ResourceManager.GetString("order_status_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Awaiting for Shipment 等待发货 的本地化字符串。
        /// </summary>
        internal static string order_status_7 {
            get {
                return ResourceManager.GetString("order_status_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Work Order Finished 工单完成 的本地化字符串。
        /// </summary>
        internal static string order_status_8 {
            get {
                return ResourceManager.GetString("order_status_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password 密码 的本地化字符串。
        /// </summary>
        internal static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Repeat Password 重复密码 的本地化字符串。
        /// </summary>
        internal static string password_repeat {
            get {
                return ResourceManager.GetString("password_repeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Post Code 邮编 的本地化字符串。
        /// </summary>
        internal static string postcode {
            get {
                return ResourceManager.GetString("postcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Module Type 工具型号 的本地化字符串。
        /// </summary>
        internal static string product_name {
            get {
                return ResourceManager.GetString("product_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Province 省份 的本地化字符串。
        /// </summary>
        internal static string province {
            get {
                return ResourceManager.GetString("province", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name 姓名 的本地化字符串。
        /// </summary>
        internal static string real_name {
            get {
                return ResourceManager.GetString("real_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remarks 备注 的本地化字符串。
        /// </summary>
        internal static string remark {
            get {
                return ResourceManager.GetString("remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Responsible Technician 跟单技术员 的本地化字符串。
        /// </summary>
        internal static string responsible_technician {
            get {
                return ResourceManager.GetString("responsible_technician", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Image 选择图片 的本地化字符串。
        /// </summary>
        internal static string select_image {
            get {
                return ResourceManager.GetString("select_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Serial Number 序列号 的本地化字符串。
        /// </summary>
        internal static string serial_number {
            get {
                return ResourceManager.GetString("serial_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Aceess to the Work Order 查看详情 的本地化字符串。
        /// </summary>
        internal static string show_detail {
            get {
                return ResourceManager.GetString("show_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Spare Part Name 备件名称 的本地化字符串。
        /// </summary>
        internal static string spare_part_name {
            get {
                return ResourceManager.GetString("spare_part_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start Time 开始时间 的本地化字符串。
        /// </summary>
        internal static string start_time {
            get {
                return ResourceManager.GetString("start_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Repair Station 维修站 的本地化字符串。
        /// </summary>
        internal static string station {
            get {
                return ResourceManager.GetString("station", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Status Update Time 状态更新时间 的本地化字符串。
        /// </summary>
        internal static string status_update_time {
            get {
                return ResourceManager.GetString("status_update_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Telephone 电话 的本地化字符串。
        /// </summary>
        internal static string telephone {
            get {
                return ResourceManager.GetString("telephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tool Function Test 工具功能测试 的本地化字符串。
        /// </summary>
        internal static string tool_function_test {
            get {
                return ResourceManager.GetString("tool_function_test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tool Assembly 工具装配 的本地化字符串。
        /// </summary>
        internal static string tool_function_test_item_text1 {
            get {
                return ResourceManager.GetString("tool_function_test_item_text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Customer Acce. 客户附件安装 的本地化字符串。
        /// </summary>
        internal static string tool_function_test_item_text2 {
            get {
                return ResourceManager.GetString("tool_function_test_item_text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Surface Clean 工具表面清洁 的本地化字符串。
        /// </summary>
        internal static string tool_function_test_item_text3 {
            get {
                return ResourceManager.GetString("tool_function_test_item_text3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Torque Test 扭矩测试 的本地化字符串。
        /// </summary>
        internal static string tool_function_test_item_text4 {
            get {
                return ResourceManager.GetString("tool_function_test_item_text4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Speed 速度 的本地化字符串。
        /// </summary>
        internal static string tool_function_test_item_text5 {
            get {
                return ResourceManager.GetString("tool_function_test_item_text5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Others 其他 的本地化字符串。
        /// </summary>
        internal static string tool_function_test_item_text6 {
            get {
                return ResourceManager.GetString("tool_function_test_item_text6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Assembly 装配 的本地化字符串。
        /// </summary>
        internal static string tool_function_test_item_text7 {
            get {
                return ResourceManager.GetString("tool_function_test_item_text7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Surface Clean 表面清洁 的本地化字符串。
        /// </summary>
        internal static string tool_function_test_item_text8 {
            get {
                return ResourceManager.GetString("tool_function_test_item_text8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tool Connection Test 工具连接测试 的本地化字符串。
        /// </summary>
        internal static string tool_function_test_item_text9 {
            get {
                return ResourceManager.GetString("tool_function_test_item_text9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tool Type 工具类型 的本地化字符串。
        /// </summary>
        internal static string tool_type {
            get {
                return ResourceManager.GetString("tool_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Updated Status 更新状态 的本地化字符串。
        /// </summary>
        internal static string update_status {
            get {
                return ResourceManager.GetString("update_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User Id 用户编号 的本地化字符串。
        /// </summary>
        internal static string userid {
            get {
                return ResourceManager.GetString("userid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User Name 用户名 的本地化字符串。
        /// </summary>
        internal static string username {
            get {
                return ResourceManager.GetString("username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User Create 用户添加 的本地化字符串。
        /// </summary>
        internal static string user_create {
            get {
                return ResourceManager.GetString("user_create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User Management 用户管理 的本地化字符串。
        /// </summary>
        internal static string user_management {
            get {
                return ResourceManager.GetString("user_management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User Search 用户查询 的本地化字符串。
        /// </summary>
        internal static string user_query {
            get {
                return ResourceManager.GetString("user_query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User Type 用户类型 的本地化字符串。
        /// </summary>
        internal static string user_type {
            get {
                return ResourceManager.GetString("user_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User Update 用户修改 的本地化字符串。
        /// </summary>
        internal static string user_update {
            get {
                return ResourceManager.GetString("user_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Work Content 工作内容 的本地化字符串。
        /// </summary>
        internal static string work_content {
            get {
                return ResourceManager.GetString("work_content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 消耗工时 的本地化字符串。
        /// </summary>
        internal static string work_time {
            get {
                return ResourceManager.GetString("work_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Requisition Type 工作类型 的本地化字符串。
        /// </summary>
        internal static string work_type {
            get {
                return ResourceManager.GetString("work_type", resourceCulture);
            }
        }
    }
}
